name: frontend
description: "Perfume Collection App - Vivino dos Perfumes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  mobile_scanner: ^6.0.2
  geolocator: ^14.0.2
  image_picker: ^1.2.3
  camera: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
